In [4]:
data_list = [1,2,3]

In [5]:
data_list

[1, 2, 3]

In [6]:
import numpy as np

In [9]:
arr = np.array(data_list)

In [10]:
arr

array([1, 2, 3])

In [11]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [12]:
arr2 = np.array(data_list2)

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr3 = np.array([1,2,3,4,5])

In [15]:
arr3

array([1, 2, 3, 4, 5])

In [16]:
arr3[0]

1

In [17]:
arr3[4]

5

In [18]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
arr2[2,2]

90

In [20]:
arr2[0,1]

20

In [21]:
arr2[5,5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [22]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [31]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [37]:
np.random.randint(0,10)

5

In [41]:
np.random.randint(15)

0

In [42]:
np.random.randint(1,10,5)

array([4, 5, 3, 1, 2])

In [44]:
np.random.rand(5)

array([0.52006476, 0.07220018, 0.9022661 , 0.26527306, 0.69857897])

In [45]:
np.random.randn(5)

array([-0.43631626, -0.28073972,  0.58604198,  0.12180464,  1.08203886])

In [46]:
arr = np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [50]:
newArray = np.random.randint(1,100,10)

In [51]:
newArray

array([85, 12, 74, 89, 12, 43, 88, 38, 67, 64])

In [52]:
newArray.max()

89

In [53]:
newArray.min()

12

In [54]:
newArray.sum()

572

In [55]:
newArray.mean()

57.2

In [56]:
newArray.argmax()

3

In [57]:
newArray.argmin()

1

In [58]:
detArray = np.random.randint(1,100,25)

In [59]:
detArray

array([11, 65, 34, 57,  7, 43, 48, 86, 24,  4, 18, 85, 51, 70, 67,  8, 57,
       69, 69, 22, 24, 55, 31, 60, 50])

In [60]:
detArray = detArray.reshape(5,5)

In [61]:
detArray

array([[11, 65, 34, 57,  7],
       [43, 48, 86, 24,  4],
       [18, 85, 51, 70, 67],
       [ 8, 57, 69, 69, 22],
       [24, 55, 31, 60, 50]])

In [62]:
np.linalg.det(detArray)

-176879685.00000063

In [63]:
detArray2 = np.array([[1,2],[3,4]])

In [64]:
detArray2

array([[1, 2],
       [3, 4]])

In [65]:
np.linalg.det(detArray2)

-2.0000000000000004

In [66]:
round(np.linalg.det(detArray2))

-2.0