In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

2

In [5]:
arr[3]

4

In [6]:
arr[1:5]

array([2, 3, 4, 5])

In [7]:
arr[:4]

array([1, 2, 3, 4])

In [8]:
arr[::2]

array([1, 3, 5, 7, 9])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[:3]

array([1, 2, 3])

In [11]:
arr[:3] = 25

In [12]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [13]:
arr = np.arange(1,10)

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2 = arr

In [29]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr2[:3] = 100

In [31]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [32]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [33]:
arr = np.arange(1,10)

In [34]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr2 = arr.copy()

In [36]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr2[:3] = 25

In [38]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [39]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
newArray = np.arange(1,21)

In [41]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
newArray = newArray.reshape(5,4)

In [45]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
newArray[0,0]

1

In [47]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [48]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [51]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
arr = np.arange(1,11)

In [54]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
booleanArray = arr > 3

In [57]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])