## Numpy Array Indekslenmesi ve Parçalanması

In [1]:
import numpy as np

In [10]:
arr = np.arange(1,10)

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[1]

2

In [13]:
arr[2]

3

In [14]:
arr[1:5]

array([2, 3, 4, 5])

In [15]:
arr[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[:4]

array([1, 2, 3, 4])

In [17]:
arr[::2]

array([1, 3, 5, 7, 9])

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[:3] = 25

In [21]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [22]:
arr = np.arange(1,10)

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr2 = arr # Aynı değerleri gösteren iki tane değişken

In [25]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr2[:3] =  25

In [27]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [28]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [29]:
arr = np.arange(1,10)

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arrCopy = arr.copy() # Değerler kopyalanıyor.

In [32]:
arrCopy[:3] = 25

In [33]:
arrCopy

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [34]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
newArray = np.arange(1,21)

In [37]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
newArray = newArray.reshape(4,5)

In [43]:
newArray[0,0]

1

In [45]:
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
newArray[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [47]:
newArray[:2,:2]

array([[1, 2],
       [6, 7]])

In [49]:
newArray[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Numpy Arraylerinin Filtrelenmesi

In [50]:
arr = np.arange(1,10)

In [51]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [54]:
boolValuesArray = arr > 3

In [55]:
boolValuesArray

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [56]:
arr[boolValuesArray] # True olanlar filtrelenir.

array([4, 5, 6, 7, 8, 9])

In [58]:
arr[arr > 5] # Daha kısa hali.

array([6, 7, 8, 9])