## Numpy Array Oluşturma Yöntemleri

In [1]:
data_list = [1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [8]:
arr = np.array(data_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [11]:
arr2 = np.array(data_list2)

In [12]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
arr

array([1, 2, 3])

In [14]:
arr[1]

2

In [15]:
arr[2]

3

In [16]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
arr2[2,2]

90

In [27]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.linspace(0,100,5) # 0 ile 100 arası değerleri 5 parçaya böler.

array([  0.,  25.,  50.,  75., 100.])

In [38]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [39]:
np.eye(6) # Birim Matris Oluşturur.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
np.random.randint(0,10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

3

In [52]:
np.random.randint(10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

9

In [56]:
np.random.randint(1,10,5) # 1(dahil) ile 10(hariç) arasında 5 değer oluşturarak 5 değer saklayan array oluşturur.

array([7, 9, 6, 1, 5])

In [60]:
np.random.rand(5) # 0 ile 1 arasında 5 float değerler oluşturur.

array([0.31801013, 0.43973085, 0.44581445, 0.67724802, 0.41159006])

In [61]:
np.random.randn(10) # 0 etrafında - ve + değerlerle Gaussian Distribution'a göre değerler oluşturur.

array([-1.67155361,  0.5474927 , -1.07769193,  0.14089541,  0.63481647,
        0.30553815, -1.1648442 , -0.18526607,  1.97819333, -0.24172663])

In [63]:
arr = np.arange(25)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
arr.reshape(5,5) # 5 x 5 =  25 tek boyutlu matrisi 2 boyuta çevirir.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
arr.reshape(4,5) # 4 x 5 25'e eşit olmadığından çeviremez ve hata verir.

ValueError: cannot reshape array of size 25 into shape (4,5)

In [68]:
newArray = np.random.randint(1,100,10)

In [69]:
newArray

array([85, 85, 62, 25, 59, 78, 22, 91, 78, 58])

In [71]:
newArray.max()

91

In [72]:
newArray.min()

22

In [76]:
newArray.sum() # Tüm değerlerin toplamı

643

In [77]:
newArray.mean() # Ortalama Bulur 

64.3

In [82]:
newArray.argmin() # En küçük eleman 6.indekste

6

In [80]:
newArray.argmax() # En büyük eleman 7.indekste

7

## Tekrar ve Determinant Hesaplama

In [83]:
detArray =  np.random.randint(1,100,25)

In [84]:
detArray

array([ 5, 54, 55, 62, 83, 73, 52, 62,  8, 95, 64, 82, 27, 79, 58, 23,  9,
       34, 25, 30, 40, 58, 97, 75, 36])

In [87]:
detArray = detArray.reshape(5,5)

In [88]:
detArray

array([[ 5, 54, 55, 62, 83],
       [73, 52, 62,  8, 95],
       [64, 82, 27, 79, 58],
       [23,  9, 34, 25, 30],
       [40, 58, 97, 75, 36]])

In [89]:
np.linalg.det(detArray)

-802623845.9999968

In [90]:
round(np.linalg.det(detArray))

-802623846.0

In [91]:
detArray2 = np.array([[1,2],[3,4]])

In [92]:
round(np.linalg.det(detArray2))

-2.0